blank_issues_enabled: true
contact_links:
  - name: Запросить иное
    url: https://discord.gg/9WYK4Ues7X
    about: Отправляйте запросы на добавление новых функций в наш [Дискорд](https://discord.gg/9WYK4Ues7X.
