- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#ff178b"
  weight: 15 # ss14-art-edit
  roles:
  # - Magistrate # ss14-art-edit
  - IAA
  - Lawyer
  # editorHidden: true # ss14-art-edit
  primary: false

- type: department
  id: Representatives
  name: department-NT
  description: department-NT-description
  editorHidden: true # ss14-art-edit
  color: "#05255D"
  roles:
  # ss14-art-edit start
  # - BlueShield
  # - Magistrate
  # - NanoTrasenRepresentative
  # - StationAi
  # - IAA
  # - NanotrasenCareerTrainer
  # ss14-art-edit end
  - Decimus
  - NanoTrasenSpecialForces
  - NTNCBlueShield
  primary: false
  weight: 50

- type: department
  id: TSF
  name: department-TSF
  description: department-TSF
  color: "#22a7ff"
  roles:
  - SolGovOfficer
  - SolGovOfficerSheriff
  - TSFMCCrew
  - TSFMarine
  - TSFMarineElite
  editorHidden: true
